.TH SKRYPT 1 "2017-06-12" "1.0" "Skrypt Man Page"
.SH NAZWA
Skrypt - wyszukiwarka plikow mp3.
.SH SKLADNIA
duzyskrypt [OPTIONS]
.SH OPIS
Skrypt pozwalajacy wyszukac pliki mp3 w danym folderze wedlug ich tagow: tytul, wykonawca, album, gatunek, rok wydania
.SH OPCJE
.TP
.BI \-f " FOLDER"
Mozliwosc wybrania folderu, w ktorym wyszukiwarka ma znalezc pliki. W przypadku nie wpisania folderu, pliki beda wyszukiwane w folderze, w ktorym znajduje sie wyszukiwarka.
.TP
.BI \-t " TYTUL"
Mozliwosc wybrania tytulu wyszukiwanej piosenki.
.TP
.BI \-w " WYKONAWCA"
Mozliwosc wybrania autora wyszukiwanej piosenki.
.TP
.BI \-a " ALBUM"
Mozliwosc wybrania albumu, z ktorego pochodzi wyszukiwana piosenka.
.TP
.BI \-g " GATUNEK"
Mozliwosc wybrania gatunku wyszukiwanej piosenki.
.TP
.BI \-r " ROK"
Mozliwosc wybrania roku wydania wyszukiwanej piosenki.
.SH DZIALANIE PROGRAMU
Po wlaczeniu wyszukiwarki zostaje ukazane menu z opcjami tagow podanymi w opisie wraz z uzupelnionymi danymi podanymi przy wlaczaniu skryptu. Uzytkownik moze przed wyszukiwaniem dodac, usunac lub zmienic wybrane tagi. Po wybraniu opcji "wyszukaj" ukazana zostanie lista plikow mp3 spelniajaca wybrane warunki.
.SH AUTOR
Copyright 2017 Patryk Pardej
